name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token
      - name: create-repo
        id: create_repo
        run: |
          output=$(gh repo create dowon-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme)
          echo "::set-output name=result::$output"
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "pretext": "create repo result",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "create repo result ${{ steps.create_repo.outcome }}",
                      "short": true,
                      "value": "${{ inputs.prefix }}-${{ inputs.name }}\n${{ steps.create_repo.outputs.result }}"
                    } 
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
