name: pull-request-workflow
#  types: [opened] 이건 pull request가 생성된 그 시점에만 실행되게 하는것 아니면 pull request를 생성하지 않아도 지속적으로 실행된다.
on:
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world-1
          echo hello world-2
