name: workflow-dispatch
on:
  workflow-dispatch:
    inputs:
      name:
        description: "set name"
        required: true
        default: "github-actions"
        type: string
      environment:
        description: "set env"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo dispatch
      - name: step2
        run: |
          echo dispatch 1
          echo dispatch 2
      - name: step3
        run: |
          echo ${{ inputs.name }}
          echo ${{ inputs.environment }}
